### ISSUE TITLE
Running shinyMixR scripts in Windows

### ISSUE THREAD

**Issue by WouterAh** [RichardHooijmaijers/shinyMixR#16]
Hi @RichardHooijmaijers and the shinyMixR team,
 
I'm currently working on building a PK model in nlmixr2 and am very interested in using shinyMixR as an interface for running nlmixr2. However, while I was working with the shinyMixR package I encountered an issue with running scripts on my windows operating system. The error message that I receive is as follows: 

Error: '\U' used without hex digits in character string starting "'C:\U" Execution halted 

When looking for the cause of this error in the source code I found out that the code in lines 24 and 25 of the "scriptfuncSRV" function lies at the root of this error, since: writeLines(c(paste0("setwd('", normalizePath("."),"')") for some reason writes the following to the script that I'm trying to run: setwd('C:\Users\xxxx') with singular backwards slashes instead of a "/" or two backwards slashes. 

Now for my question, I was wondering if you are aware that this issue can occur and if you have a potential solution. I tried changing my working directory in multiple different ways, however, R keeps writing setwd() to the script that I'm trying to use with singular backwards slashes, ultimately resulting in the presented error and me being unable to run the script from within shinyMixR. (An idea that I had was to explicitly specify the slash to use as: winslash = "/" in the normalizePath() function, which did seem to work when I tested the code in a separate R file)

I look forward to hearing from you!

Best regards,
Wouter

**Comment by RichardHooijmaijers** [comment]
Hi @WouterAh 

Thanks for your interest in the package and for picking up this issue. I did not notice it earlier because most of the development and testing was done on either linux or mac. 

I looked into it and I think your suggestion with `winslash="/"` works best. I have uploaded a new version and ran a few tests in a windows environment. Everything seems to work as expected, so you can re-install the package using `devtools::install_github("richardhooijmaijers/shinyMixR")`

Let me know if you are still encountering problems or if you have any other issues or suggestions.

Best,
Richard

**Comment by WouterAh** [comment]
Hi Richard,

Thanks a lot for your quick response and update, I'm able to run scripts from within shinyMixR now. If any other issues or suggestions come up during my work in shinyMixR I'll make sure to let you know!

Best,
Wouter
